---
id: aws-cli
name: AWS CLI v2
defaultVersion: 2.25.14
layout: directory
paths: dist
executable: dist/aws
packaging: ZIP_STRIP
osMappings:
  Linux: linux
archMappings:
  x86_64: x86_64
  arm64: aarch64
linuxUrlTemplate: https://awscli.amazonaws.com/awscli-exe-linux-{arch}-{version}.zip
