quarkus.banner.enabled=false
# There is no upx mac arm
#quarkus.native.compression.level=5
%prod.quarkus.log.level=ERROR
quarkus.native.resources.includes=provisioRoot/**,project.properties
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.commons.compress.compressors.zstandard.ZstdCompressorInputStream
