name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs'
      - README.md
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '25'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify GraalVM
        run: native-image --version
      - name: Build
        run: ./mvnw clean package -B -Pnative
